import crypto from 'crypto';
import { Pool, PoolClient } from 'pg';

export interface TransactionRecord { id: string; type: string; amount: number; fee: number; balanceAfter: number; ts: string; }
export interface UserProfile { id: string; username: string; avatar: string; token: string; balance: number; history: TransactionRecord[]; createdAt: number; vaultedPaymentMethod?: Record<string, string>; }

if (!process.env.DATABASE_URL) throw new Error('DATABASE_URL is required; local JSON storage is no longer supported.');
export const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized: false } : undefined });
let ready: Promise<void> | null = null;
async function init() {
  if (ready) return ready;
  ready = (async () => {
    await pool.query(`CREATE TABLE IF NOT EXISTS users (id text PRIMARY KEY, username text NOT NULL, avatar text NOT NULL, token_hash text UNIQUE NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), vaulted_payment_method jsonb); CREATE TABLE IF NOT EXISTS accounts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id text UNIQUE REFERENCES users(id), kind text NOT NULL, name text NOT NULL, match_id text UNIQUE, created_at timestamptz NOT NULL DEFAULT now()); CREATE TABLE IF NOT EXISTS ledger_transactions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), from_account uuid NOT NULL REFERENCES accounts(id), to_account uuid NOT NULL REFERENCES accounts(id), amount numeric(18,2) NOT NULL CHECK (amount > 0), type text NOT NULL, fee numeric(18,2) NOT NULL DEFAULT 0, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now()); CREATE INDEX IF NOT EXISTS ledger_from_idx ON ledger_transactions(from_account); CREATE INDEX IF NOT EXISTS ledger_to_idx ON ledger_transactions(to_account);`);
    await pool.query(`CREATE EXTENSION IF NOT EXISTS pgcrypto`);
  })();
  return ready;
}
const hash = (v: string) => crypto.createHash('sha256').update(v).digest('hex');
async function system(client: PoolClient) { const r = await client.query(`SELECT id FROM accounts WHERE kind='system' LIMIT 1`); if (r.rowCount) return r.rows[0].id; return (await client.query(`INSERT INTO accounts(kind,name) VALUES('system','System Coffer') RETURNING id`)).rows[0].id; }
async function userByToken(token: string, client = pool) { if (!token) return null; const r = await client.query(`SELECT * FROM users WHERE token_hash=$1`, [hash(token)]); return r.rows[0] || null; }
async function balance(account: string, client = pool) { const r = await client.query(`SELECT COALESCE(SUM(CASE WHEN to_account=$1 THEN amount ELSE 0 END),0)-COALESCE(SUM(CASE WHEN from_account=$1 THEN amount ELSE 0 END),0) AS balance FROM ledger_transactions WHERE to_account=$1 OR from_account=$1`, [account]); return Number(r.rows[0].balance); }
async function history(account: string, client = pool): Promise<TransactionRecord[]> { const r = await client.query(`SELECT id,type,amount,fee,created_at,metadata FROM ledger_transactions WHERE from_account=$1 OR to_account=$1 ORDER BY created_at DESC LIMIT 100`, [account]); let running = await balance(account, client); return r.rows.map(x => { const amount=Number(x.amount), fee=Number(x.fee); const incoming=x.to_account===account; const after=running; running += incoming ? -amount : amount; return { id:x.id, type:x.type, amount, fee, balanceAfter:after, ts:new Date(x.created_at).toLocaleTimeString() }; }); }
async function profile(user: any, client = pool): Promise<UserProfile> { const a=(await client.query(`SELECT id FROM accounts WHERE user_id=$1`,[user.id])).rows[0]; const b=await balance(a.id,client); return { id:user.id, username:user.username, avatar:user.avatar, token:user._token || '', balance:b, history:await history(a.id,client), createdAt:new Date(user.created_at).getTime(), vaultedPaymentMethod:user.vaulted_payment_method || undefined }; }
async function transfer(client: PoolClient, from: string, to: string, amount: number, type: string, fee=0, metadata={}) { await client.query(`INSERT INTO ledger_transactions(from_account,to_account,amount,type,fee,metadata) VALUES($1,$2,$3,$4,$5,$6)`,[from,to,amount,type,fee,metadata]); }
export class Database {
 static async createUser(username:string, avatar:string) { await init(); const c=await pool.connect(); try { await c.query('BEGIN'); const token=`tok_${crypto.randomBytes(24).toString('hex')}`, id=`usr_${crypto.randomBytes(8).toString('hex')}`; const u=(await c.query(`INSERT INTO users(id,username,avatar,token_hash) VALUES($1,$2,$3,$4) RETURNING *`,[id,username.trim()||'Player',avatar||'JP',hash(token)])).rows[0]; await c.query(`INSERT INTO accounts(user_id,kind,name) VALUES($1,'user',$2)`,[id,u.username]); await c.query('COMMIT'); u._token=token; return profile(u,c); } catch(e){await c.query('ROLLBACK');throw e} finally{c.release()} }
 static async getUserByToken(token:string){ await init(); return userByToken(token); }
 static async updateUserProfile(token:string, updates:any){ await init(); const u=await userByToken(token); if(!u)return null; const r=await pool.query(`UPDATE users SET username=COALESCE(NULLIF($1,''),username), avatar=COALESCE(NULLIF($2,''),avatar) WHERE id=$3 RETURNING *`,[updates.username,updates.avatar,u.id]); return profile(r.rows[0]); }
 static async mutate(token:string, amount:number, type:string, fee=0, payment?:any, label?:string){ await init(); const c=await pool.connect(); try {await c.query('BEGIN'); const u=await userByToken(token,c); if(!u) {await c.query('ROLLBACK');return null;} const ua=(await c.query(`SELECT id FROM accounts WHERE user_id=$1 FOR UPDATE`,[u.id])).rows[0].id; const sys=await system(c); if(['Withdraw','Buy-in'].includes(type) && await balance(ua,c)<amount){await c.query('ROLLBACK');return null;} if(payment) await c.query(`UPDATE users SET vaulted_payment_method=$1 WHERE id=$2`,[payment,u.id]); const incoming=['Deposit','Winnings'].includes(type); await transfer(c,incoming?sys:ua,incoming?ua:sys,amount,type,fee,{label}); await c.query('COMMIT'); const fresh=(await c.query('SELECT * FROM users WHERE id=$1',[u.id])).rows[0]; return {user:await profile(fresh,c),tx:{type,amount,fee},payout:Math.round((amount-fee)*100)/100}; } catch(e){await c.query('ROLLBACK');throw e} finally{c.release()} }
 static async deposit(t:string,a:number,f:number,p?:any){return this.mutate(t,a,'Deposit',f,p)} static async withdraw(t:string,a:number,f:number){return this.mutate(t,a,'Withdraw',f)} static async charge(t:string,a:number,l='Buy-in'){return this.mutate(t,a,'Buy-in',0,undefined,l)} static async credit(t:string,a:number,l='Winnings'){return this.mutate(t,a,'Winnings',0,undefined,l)}
}
